# Generated by Django 5.2.8 on 2025-12-09 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_mlmodel_prediction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signalement',
            old_name='civil',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='image',
            name='signalement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.signalement'),
        ),
    ]
